# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/Documents/gfx-framework-master

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/Documents/gfx-framework-master

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Documents/gfx-framework-master/CMakeFiles /home/student/Documents/gfx-framework-master//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Documents/gfx-framework-master/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GFXFramework

# Build rule for target.
GFXFramework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GFXFramework
.PHONY : GFXFramework

# fast build rule for target.
GFXFramework/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/build
.PHONY : GFXFramework/fast

src/components/camera_input.o: src/components/camera_input.cpp.o
.PHONY : src/components/camera_input.o

# target to build an object file
src/components/camera_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/camera_input.cpp.o
.PHONY : src/components/camera_input.cpp.o

src/components/camera_input.i: src/components/camera_input.cpp.i
.PHONY : src/components/camera_input.i

# target to preprocess a source file
src/components/camera_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/camera_input.cpp.i
.PHONY : src/components/camera_input.cpp.i

src/components/camera_input.s: src/components/camera_input.cpp.s
.PHONY : src/components/camera_input.s

# target to generate assembly for a file
src/components/camera_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/camera_input.cpp.s
.PHONY : src/components/camera_input.cpp.s

src/components/scene_input.o: src/components/scene_input.cpp.o
.PHONY : src/components/scene_input.o

# target to build an object file
src/components/scene_input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/scene_input.cpp.o
.PHONY : src/components/scene_input.cpp.o

src/components/scene_input.i: src/components/scene_input.cpp.i
.PHONY : src/components/scene_input.i

# target to preprocess a source file
src/components/scene_input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/scene_input.cpp.i
.PHONY : src/components/scene_input.cpp.i

src/components/scene_input.s: src/components/scene_input.cpp.s
.PHONY : src/components/scene_input.s

# target to generate assembly for a file
src/components/scene_input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/scene_input.cpp.s
.PHONY : src/components/scene_input.cpp.s

src/components/simple_scene.o: src/components/simple_scene.cpp.o
.PHONY : src/components/simple_scene.o

# target to build an object file
src/components/simple_scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/simple_scene.cpp.o
.PHONY : src/components/simple_scene.cpp.o

src/components/simple_scene.i: src/components/simple_scene.cpp.i
.PHONY : src/components/simple_scene.i

# target to preprocess a source file
src/components/simple_scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/simple_scene.cpp.i
.PHONY : src/components/simple_scene.cpp.i

src/components/simple_scene.s: src/components/simple_scene.cpp.s
.PHONY : src/components/simple_scene.s

# target to generate assembly for a file
src/components/simple_scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/simple_scene.cpp.s
.PHONY : src/components/simple_scene.cpp.s

src/components/text_renderer.o: src/components/text_renderer.cpp.o
.PHONY : src/components/text_renderer.o

# target to build an object file
src/components/text_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/text_renderer.cpp.o
.PHONY : src/components/text_renderer.cpp.o

src/components/text_renderer.i: src/components/text_renderer.cpp.i
.PHONY : src/components/text_renderer.i

# target to preprocess a source file
src/components/text_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/text_renderer.cpp.i
.PHONY : src/components/text_renderer.cpp.i

src/components/text_renderer.s: src/components/text_renderer.cpp.s
.PHONY : src/components/text_renderer.s

# target to generate assembly for a file
src/components/text_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/components/text_renderer.cpp.s
.PHONY : src/components/text_renderer.cpp.s

src/core/engine.o: src/core/engine.cpp.o
.PHONY : src/core/engine.o

# target to build an object file
src/core/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/engine.cpp.o
.PHONY : src/core/engine.cpp.o

src/core/engine.i: src/core/engine.cpp.i
.PHONY : src/core/engine.i

# target to preprocess a source file
src/core/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/engine.cpp.i
.PHONY : src/core/engine.cpp.i

src/core/engine.s: src/core/engine.cpp.s
.PHONY : src/core/engine.s

# target to generate assembly for a file
src/core/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/engine.cpp.s
.PHONY : src/core/engine.cpp.s

src/core/gpu/frame_buffer.o: src/core/gpu/frame_buffer.cpp.o
.PHONY : src/core/gpu/frame_buffer.o

# target to build an object file
src/core/gpu/frame_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/frame_buffer.cpp.o
.PHONY : src/core/gpu/frame_buffer.cpp.o

src/core/gpu/frame_buffer.i: src/core/gpu/frame_buffer.cpp.i
.PHONY : src/core/gpu/frame_buffer.i

# target to preprocess a source file
src/core/gpu/frame_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/frame_buffer.cpp.i
.PHONY : src/core/gpu/frame_buffer.cpp.i

src/core/gpu/frame_buffer.s: src/core/gpu/frame_buffer.cpp.s
.PHONY : src/core/gpu/frame_buffer.s

# target to generate assembly for a file
src/core/gpu/frame_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/frame_buffer.cpp.s
.PHONY : src/core/gpu/frame_buffer.cpp.s

src/core/gpu/gpu_buffers.o: src/core/gpu/gpu_buffers.cpp.o
.PHONY : src/core/gpu/gpu_buffers.o

# target to build an object file
src/core/gpu/gpu_buffers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/gpu_buffers.cpp.o
.PHONY : src/core/gpu/gpu_buffers.cpp.o

src/core/gpu/gpu_buffers.i: src/core/gpu/gpu_buffers.cpp.i
.PHONY : src/core/gpu/gpu_buffers.i

# target to preprocess a source file
src/core/gpu/gpu_buffers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/gpu_buffers.cpp.i
.PHONY : src/core/gpu/gpu_buffers.cpp.i

src/core/gpu/gpu_buffers.s: src/core/gpu/gpu_buffers.cpp.s
.PHONY : src/core/gpu/gpu_buffers.s

# target to generate assembly for a file
src/core/gpu/gpu_buffers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/gpu_buffers.cpp.s
.PHONY : src/core/gpu/gpu_buffers.cpp.s

src/core/gpu/mesh.o: src/core/gpu/mesh.cpp.o
.PHONY : src/core/gpu/mesh.o

# target to build an object file
src/core/gpu/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/mesh.cpp.o
.PHONY : src/core/gpu/mesh.cpp.o

src/core/gpu/mesh.i: src/core/gpu/mesh.cpp.i
.PHONY : src/core/gpu/mesh.i

# target to preprocess a source file
src/core/gpu/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/mesh.cpp.i
.PHONY : src/core/gpu/mesh.cpp.i

src/core/gpu/mesh.s: src/core/gpu/mesh.cpp.s
.PHONY : src/core/gpu/mesh.s

# target to generate assembly for a file
src/core/gpu/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/mesh.cpp.s
.PHONY : src/core/gpu/mesh.cpp.s

src/core/gpu/shader.o: src/core/gpu/shader.cpp.o
.PHONY : src/core/gpu/shader.o

# target to build an object file
src/core/gpu/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/shader.cpp.o
.PHONY : src/core/gpu/shader.cpp.o

src/core/gpu/shader.i: src/core/gpu/shader.cpp.i
.PHONY : src/core/gpu/shader.i

# target to preprocess a source file
src/core/gpu/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/shader.cpp.i
.PHONY : src/core/gpu/shader.cpp.i

src/core/gpu/shader.s: src/core/gpu/shader.cpp.s
.PHONY : src/core/gpu/shader.s

# target to generate assembly for a file
src/core/gpu/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/shader.cpp.s
.PHONY : src/core/gpu/shader.cpp.s

src/core/gpu/texture2D.o: src/core/gpu/texture2D.cpp.o
.PHONY : src/core/gpu/texture2D.o

# target to build an object file
src/core/gpu/texture2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/texture2D.cpp.o
.PHONY : src/core/gpu/texture2D.cpp.o

src/core/gpu/texture2D.i: src/core/gpu/texture2D.cpp.i
.PHONY : src/core/gpu/texture2D.i

# target to preprocess a source file
src/core/gpu/texture2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/texture2D.cpp.i
.PHONY : src/core/gpu/texture2D.cpp.i

src/core/gpu/texture2D.s: src/core/gpu/texture2D.cpp.s
.PHONY : src/core/gpu/texture2D.s

# target to generate assembly for a file
src/core/gpu/texture2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/gpu/texture2D.cpp.s
.PHONY : src/core/gpu/texture2D.cpp.s

src/core/managers/texture_manager.o: src/core/managers/texture_manager.cpp.o
.PHONY : src/core/managers/texture_manager.o

# target to build an object file
src/core/managers/texture_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/managers/texture_manager.cpp.o
.PHONY : src/core/managers/texture_manager.cpp.o

src/core/managers/texture_manager.i: src/core/managers/texture_manager.cpp.i
.PHONY : src/core/managers/texture_manager.i

# target to preprocess a source file
src/core/managers/texture_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/managers/texture_manager.cpp.i
.PHONY : src/core/managers/texture_manager.cpp.i

src/core/managers/texture_manager.s: src/core/managers/texture_manager.cpp.s
.PHONY : src/core/managers/texture_manager.s

# target to generate assembly for a file
src/core/managers/texture_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/managers/texture_manager.cpp.s
.PHONY : src/core/managers/texture_manager.cpp.s

src/core/window/input_controller.o: src/core/window/input_controller.cpp.o
.PHONY : src/core/window/input_controller.o

# target to build an object file
src/core/window/input_controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/input_controller.cpp.o
.PHONY : src/core/window/input_controller.cpp.o

src/core/window/input_controller.i: src/core/window/input_controller.cpp.i
.PHONY : src/core/window/input_controller.i

# target to preprocess a source file
src/core/window/input_controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/input_controller.cpp.i
.PHONY : src/core/window/input_controller.cpp.i

src/core/window/input_controller.s: src/core/window/input_controller.cpp.s
.PHONY : src/core/window/input_controller.s

# target to generate assembly for a file
src/core/window/input_controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/input_controller.cpp.s
.PHONY : src/core/window/input_controller.cpp.s

src/core/window/window_callbacks.o: src/core/window/window_callbacks.cpp.o
.PHONY : src/core/window/window_callbacks.o

# target to build an object file
src/core/window/window_callbacks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_callbacks.cpp.o
.PHONY : src/core/window/window_callbacks.cpp.o

src/core/window/window_callbacks.i: src/core/window/window_callbacks.cpp.i
.PHONY : src/core/window/window_callbacks.i

# target to preprocess a source file
src/core/window/window_callbacks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_callbacks.cpp.i
.PHONY : src/core/window/window_callbacks.cpp.i

src/core/window/window_callbacks.s: src/core/window/window_callbacks.cpp.s
.PHONY : src/core/window/window_callbacks.s

# target to generate assembly for a file
src/core/window/window_callbacks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_callbacks.cpp.s
.PHONY : src/core/window/window_callbacks.cpp.s

src/core/window/window_object.o: src/core/window/window_object.cpp.o
.PHONY : src/core/window/window_object.o

# target to build an object file
src/core/window/window_object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_object.cpp.o
.PHONY : src/core/window/window_object.cpp.o

src/core/window/window_object.i: src/core/window/window_object.cpp.i
.PHONY : src/core/window/window_object.i

# target to preprocess a source file
src/core/window/window_object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_object.cpp.i
.PHONY : src/core/window/window_object.cpp.i

src/core/window/window_object.s: src/core/window/window_object.cpp.s
.PHONY : src/core/window/window_object.s

# target to generate assembly for a file
src/core/window/window_object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/window/window_object.cpp.s
.PHONY : src/core/window/window_object.cpp.s

src/core/world.o: src/core/world.cpp.o
.PHONY : src/core/world.o

# target to build an object file
src/core/world.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/world.cpp.o
.PHONY : src/core/world.cpp.o

src/core/world.i: src/core/world.cpp.i
.PHONY : src/core/world.i

# target to preprocess a source file
src/core/world.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/world.cpp.i
.PHONY : src/core/world.cpp.i

src/core/world.s: src/core/world.cpp.s
.PHONY : src/core/world.s

# target to generate assembly for a file
src/core/world.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/core/world.cpp.s
.PHONY : src/core/world.cpp.s

src/lab_m1/Tema1/Cloud.o: src/lab_m1/Tema1/Cloud.cpp.o
.PHONY : src/lab_m1/Tema1/Cloud.o

# target to build an object file
src/lab_m1/Tema1/Cloud.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Cloud.cpp.o
.PHONY : src/lab_m1/Tema1/Cloud.cpp.o

src/lab_m1/Tema1/Cloud.i: src/lab_m1/Tema1/Cloud.cpp.i
.PHONY : src/lab_m1/Tema1/Cloud.i

# target to preprocess a source file
src/lab_m1/Tema1/Cloud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Cloud.cpp.i
.PHONY : src/lab_m1/Tema1/Cloud.cpp.i

src/lab_m1/Tema1/Cloud.s: src/lab_m1/Tema1/Cloud.cpp.s
.PHONY : src/lab_m1/Tema1/Cloud.s

# target to generate assembly for a file
src/lab_m1/Tema1/Cloud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Cloud.cpp.s
.PHONY : src/lab_m1/Tema1/Cloud.cpp.s

src/lab_m1/Tema1/Explosion.o: src/lab_m1/Tema1/Explosion.cpp.o
.PHONY : src/lab_m1/Tema1/Explosion.o

# target to build an object file
src/lab_m1/Tema1/Explosion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Explosion.cpp.o
.PHONY : src/lab_m1/Tema1/Explosion.cpp.o

src/lab_m1/Tema1/Explosion.i: src/lab_m1/Tema1/Explosion.cpp.i
.PHONY : src/lab_m1/Tema1/Explosion.i

# target to preprocess a source file
src/lab_m1/Tema1/Explosion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Explosion.cpp.i
.PHONY : src/lab_m1/Tema1/Explosion.cpp.i

src/lab_m1/Tema1/Explosion.s: src/lab_m1/Tema1/Explosion.cpp.s
.PHONY : src/lab_m1/Tema1/Explosion.s

# target to generate assembly for a file
src/lab_m1/Tema1/Explosion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Explosion.cpp.s
.PHONY : src/lab_m1/Tema1/Explosion.cpp.s

src/lab_m1/Tema1/Projectile.o: src/lab_m1/Tema1/Projectile.cpp.o
.PHONY : src/lab_m1/Tema1/Projectile.o

# target to build an object file
src/lab_m1/Tema1/Projectile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Projectile.cpp.o
.PHONY : src/lab_m1/Tema1/Projectile.cpp.o

src/lab_m1/Tema1/Projectile.i: src/lab_m1/Tema1/Projectile.cpp.i
.PHONY : src/lab_m1/Tema1/Projectile.i

# target to preprocess a source file
src/lab_m1/Tema1/Projectile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Projectile.cpp.i
.PHONY : src/lab_m1/Tema1/Projectile.cpp.i

src/lab_m1/Tema1/Projectile.s: src/lab_m1/Tema1/Projectile.cpp.s
.PHONY : src/lab_m1/Tema1/Projectile.s

# target to generate assembly for a file
src/lab_m1/Tema1/Projectile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Projectile.cpp.s
.PHONY : src/lab_m1/Tema1/Projectile.cpp.s

src/lab_m1/Tema1/Tank.o: src/lab_m1/Tema1/Tank.cpp.o
.PHONY : src/lab_m1/Tema1/Tank.o

# target to build an object file
src/lab_m1/Tema1/Tank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Tank.cpp.o
.PHONY : src/lab_m1/Tema1/Tank.cpp.o

src/lab_m1/Tema1/Tank.i: src/lab_m1/Tema1/Tank.cpp.i
.PHONY : src/lab_m1/Tema1/Tank.i

# target to preprocess a source file
src/lab_m1/Tema1/Tank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Tank.cpp.i
.PHONY : src/lab_m1/Tema1/Tank.cpp.i

src/lab_m1/Tema1/Tank.s: src/lab_m1/Tema1/Tank.cpp.s
.PHONY : src/lab_m1/Tema1/Tank.s

# target to generate assembly for a file
src/lab_m1/Tema1/Tank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Tank.cpp.s
.PHONY : src/lab_m1/Tema1/Tank.cpp.s

src/lab_m1/Tema1/Tema1.o: src/lab_m1/Tema1/Tema1.cpp.o
.PHONY : src/lab_m1/Tema1/Tema1.o

# target to build an object file
src/lab_m1/Tema1/Tema1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Tema1.cpp.o
.PHONY : src/lab_m1/Tema1/Tema1.cpp.o

src/lab_m1/Tema1/Tema1.i: src/lab_m1/Tema1/Tema1.cpp.i
.PHONY : src/lab_m1/Tema1/Tema1.i

# target to preprocess a source file
src/lab_m1/Tema1/Tema1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Tema1.cpp.i
.PHONY : src/lab_m1/Tema1/Tema1.cpp.i

src/lab_m1/Tema1/Tema1.s: src/lab_m1/Tema1/Tema1.cpp.s
.PHONY : src/lab_m1/Tema1/Tema1.s

# target to generate assembly for a file
src/lab_m1/Tema1/Tema1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Tema1.cpp.s
.PHONY : src/lab_m1/Tema1/Tema1.cpp.s

src/lab_m1/Tema1/Terrain.o: src/lab_m1/Tema1/Terrain.cpp.o
.PHONY : src/lab_m1/Tema1/Terrain.o

# target to build an object file
src/lab_m1/Tema1/Terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Terrain.cpp.o
.PHONY : src/lab_m1/Tema1/Terrain.cpp.o

src/lab_m1/Tema1/Terrain.i: src/lab_m1/Tema1/Terrain.cpp.i
.PHONY : src/lab_m1/Tema1/Terrain.i

# target to preprocess a source file
src/lab_m1/Tema1/Terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Terrain.cpp.i
.PHONY : src/lab_m1/Tema1/Terrain.cpp.i

src/lab_m1/Tema1/Terrain.s: src/lab_m1/Tema1/Terrain.cpp.s
.PHONY : src/lab_m1/Tema1/Terrain.s

# target to generate assembly for a file
src/lab_m1/Tema1/Terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/Terrain.cpp.s
.PHONY : src/lab_m1/Tema1/Terrain.cpp.s

src/lab_m1/Tema1/object2D1.o: src/lab_m1/Tema1/object2D1.cpp.o
.PHONY : src/lab_m1/Tema1/object2D1.o

# target to build an object file
src/lab_m1/Tema1/object2D1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/object2D1.cpp.o
.PHONY : src/lab_m1/Tema1/object2D1.cpp.o

src/lab_m1/Tema1/object2D1.i: src/lab_m1/Tema1/object2D1.cpp.i
.PHONY : src/lab_m1/Tema1/object2D1.i

# target to preprocess a source file
src/lab_m1/Tema1/object2D1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/object2D1.cpp.i
.PHONY : src/lab_m1/Tema1/object2D1.cpp.i

src/lab_m1/Tema1/object2D1.s: src/lab_m1/Tema1/object2D1.cpp.s
.PHONY : src/lab_m1/Tema1/object2D1.s

# target to generate assembly for a file
src/lab_m1/Tema1/object2D1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/Tema1/object2D1.cpp.s
.PHONY : src/lab_m1/Tema1/object2D1.cpp.s

src/lab_m1/lab1/lab1.o: src/lab_m1/lab1/lab1.cpp.o
.PHONY : src/lab_m1/lab1/lab1.o

# target to build an object file
src/lab_m1/lab1/lab1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab1/lab1.cpp.o
.PHONY : src/lab_m1/lab1/lab1.cpp.o

src/lab_m1/lab1/lab1.i: src/lab_m1/lab1/lab1.cpp.i
.PHONY : src/lab_m1/lab1/lab1.i

# target to preprocess a source file
src/lab_m1/lab1/lab1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab1/lab1.cpp.i
.PHONY : src/lab_m1/lab1/lab1.cpp.i

src/lab_m1/lab1/lab1.s: src/lab_m1/lab1/lab1.cpp.s
.PHONY : src/lab_m1/lab1/lab1.s

# target to generate assembly for a file
src/lab_m1/lab1/lab1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab1/lab1.cpp.s
.PHONY : src/lab_m1/lab1/lab1.cpp.s

src/lab_m1/lab2/lab2.o: src/lab_m1/lab2/lab2.cpp.o
.PHONY : src/lab_m1/lab2/lab2.o

# target to build an object file
src/lab_m1/lab2/lab2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab2/lab2.cpp.o
.PHONY : src/lab_m1/lab2/lab2.cpp.o

src/lab_m1/lab2/lab2.i: src/lab_m1/lab2/lab2.cpp.i
.PHONY : src/lab_m1/lab2/lab2.i

# target to preprocess a source file
src/lab_m1/lab2/lab2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab2/lab2.cpp.i
.PHONY : src/lab_m1/lab2/lab2.cpp.i

src/lab_m1/lab2/lab2.s: src/lab_m1/lab2/lab2.cpp.s
.PHONY : src/lab_m1/lab2/lab2.s

# target to generate assembly for a file
src/lab_m1/lab2/lab2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab2/lab2.cpp.s
.PHONY : src/lab_m1/lab2/lab2.cpp.s

src/lab_m1/lab3/lab3.o: src/lab_m1/lab3/lab3.cpp.o
.PHONY : src/lab_m1/lab3/lab3.o

# target to build an object file
src/lab_m1/lab3/lab3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab3/lab3.cpp.o
.PHONY : src/lab_m1/lab3/lab3.cpp.o

src/lab_m1/lab3/lab3.i: src/lab_m1/lab3/lab3.cpp.i
.PHONY : src/lab_m1/lab3/lab3.i

# target to preprocess a source file
src/lab_m1/lab3/lab3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab3/lab3.cpp.i
.PHONY : src/lab_m1/lab3/lab3.cpp.i

src/lab_m1/lab3/lab3.s: src/lab_m1/lab3/lab3.cpp.s
.PHONY : src/lab_m1/lab3/lab3.s

# target to generate assembly for a file
src/lab_m1/lab3/lab3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab3/lab3.cpp.s
.PHONY : src/lab_m1/lab3/lab3.cpp.s

src/lab_m1/lab3/lab3_vis2D.o: src/lab_m1/lab3/lab3_vis2D.cpp.o
.PHONY : src/lab_m1/lab3/lab3_vis2D.o

# target to build an object file
src/lab_m1/lab3/lab3_vis2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab3/lab3_vis2D.cpp.o
.PHONY : src/lab_m1/lab3/lab3_vis2D.cpp.o

src/lab_m1/lab3/lab3_vis2D.i: src/lab_m1/lab3/lab3_vis2D.cpp.i
.PHONY : src/lab_m1/lab3/lab3_vis2D.i

# target to preprocess a source file
src/lab_m1/lab3/lab3_vis2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab3/lab3_vis2D.cpp.i
.PHONY : src/lab_m1/lab3/lab3_vis2D.cpp.i

src/lab_m1/lab3/lab3_vis2D.s: src/lab_m1/lab3/lab3_vis2D.cpp.s
.PHONY : src/lab_m1/lab3/lab3_vis2D.s

# target to generate assembly for a file
src/lab_m1/lab3/lab3_vis2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab3/lab3_vis2D.cpp.s
.PHONY : src/lab_m1/lab3/lab3_vis2D.cpp.s

src/lab_m1/lab3/object2D.o: src/lab_m1/lab3/object2D.cpp.o
.PHONY : src/lab_m1/lab3/object2D.o

# target to build an object file
src/lab_m1/lab3/object2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab3/object2D.cpp.o
.PHONY : src/lab_m1/lab3/object2D.cpp.o

src/lab_m1/lab3/object2D.i: src/lab_m1/lab3/object2D.cpp.i
.PHONY : src/lab_m1/lab3/object2D.i

# target to preprocess a source file
src/lab_m1/lab3/object2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab3/object2D.cpp.i
.PHONY : src/lab_m1/lab3/object2D.cpp.i

src/lab_m1/lab3/object2D.s: src/lab_m1/lab3/object2D.cpp.s
.PHONY : src/lab_m1/lab3/object2D.s

# target to generate assembly for a file
src/lab_m1/lab3/object2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab3/object2D.cpp.s
.PHONY : src/lab_m1/lab3/object2D.cpp.s

src/lab_m1/lab4/lab4.o: src/lab_m1/lab4/lab4.cpp.o
.PHONY : src/lab_m1/lab4/lab4.o

# target to build an object file
src/lab_m1/lab4/lab4.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab4/lab4.cpp.o
.PHONY : src/lab_m1/lab4/lab4.cpp.o

src/lab_m1/lab4/lab4.i: src/lab_m1/lab4/lab4.cpp.i
.PHONY : src/lab_m1/lab4/lab4.i

# target to preprocess a source file
src/lab_m1/lab4/lab4.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab4/lab4.cpp.i
.PHONY : src/lab_m1/lab4/lab4.cpp.i

src/lab_m1/lab4/lab4.s: src/lab_m1/lab4/lab4.cpp.s
.PHONY : src/lab_m1/lab4/lab4.s

# target to generate assembly for a file
src/lab_m1/lab4/lab4.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab4/lab4.cpp.s
.PHONY : src/lab_m1/lab4/lab4.cpp.s

src/lab_m1/lab5/lab5.o: src/lab_m1/lab5/lab5.cpp.o
.PHONY : src/lab_m1/lab5/lab5.o

# target to build an object file
src/lab_m1/lab5/lab5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab5/lab5.cpp.o
.PHONY : src/lab_m1/lab5/lab5.cpp.o

src/lab_m1/lab5/lab5.i: src/lab_m1/lab5/lab5.cpp.i
.PHONY : src/lab_m1/lab5/lab5.i

# target to preprocess a source file
src/lab_m1/lab5/lab5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab5/lab5.cpp.i
.PHONY : src/lab_m1/lab5/lab5.cpp.i

src/lab_m1/lab5/lab5.s: src/lab_m1/lab5/lab5.cpp.s
.PHONY : src/lab_m1/lab5/lab5.s

# target to generate assembly for a file
src/lab_m1/lab5/lab5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab5/lab5.cpp.s
.PHONY : src/lab_m1/lab5/lab5.cpp.s

src/lab_m1/lab6/lab6.o: src/lab_m1/lab6/lab6.cpp.o
.PHONY : src/lab_m1/lab6/lab6.o

# target to build an object file
src/lab_m1/lab6/lab6.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab6/lab6.cpp.o
.PHONY : src/lab_m1/lab6/lab6.cpp.o

src/lab_m1/lab6/lab6.i: src/lab_m1/lab6/lab6.cpp.i
.PHONY : src/lab_m1/lab6/lab6.i

# target to preprocess a source file
src/lab_m1/lab6/lab6.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab6/lab6.cpp.i
.PHONY : src/lab_m1/lab6/lab6.cpp.i

src/lab_m1/lab6/lab6.s: src/lab_m1/lab6/lab6.cpp.s
.PHONY : src/lab_m1/lab6/lab6.s

# target to generate assembly for a file
src/lab_m1/lab6/lab6.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab6/lab6.cpp.s
.PHONY : src/lab_m1/lab6/lab6.cpp.s

src/lab_m1/lab7/lab7.o: src/lab_m1/lab7/lab7.cpp.o
.PHONY : src/lab_m1/lab7/lab7.o

# target to build an object file
src/lab_m1/lab7/lab7.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab7/lab7.cpp.o
.PHONY : src/lab_m1/lab7/lab7.cpp.o

src/lab_m1/lab7/lab7.i: src/lab_m1/lab7/lab7.cpp.i
.PHONY : src/lab_m1/lab7/lab7.i

# target to preprocess a source file
src/lab_m1/lab7/lab7.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab7/lab7.cpp.i
.PHONY : src/lab_m1/lab7/lab7.cpp.i

src/lab_m1/lab7/lab7.s: src/lab_m1/lab7/lab7.cpp.s
.PHONY : src/lab_m1/lab7/lab7.s

# target to generate assembly for a file
src/lab_m1/lab7/lab7.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab7/lab7.cpp.s
.PHONY : src/lab_m1/lab7/lab7.cpp.s

src/lab_m1/lab8/lab8.o: src/lab_m1/lab8/lab8.cpp.o
.PHONY : src/lab_m1/lab8/lab8.o

# target to build an object file
src/lab_m1/lab8/lab8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab8/lab8.cpp.o
.PHONY : src/lab_m1/lab8/lab8.cpp.o

src/lab_m1/lab8/lab8.i: src/lab_m1/lab8/lab8.cpp.i
.PHONY : src/lab_m1/lab8/lab8.i

# target to preprocess a source file
src/lab_m1/lab8/lab8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab8/lab8.cpp.i
.PHONY : src/lab_m1/lab8/lab8.cpp.i

src/lab_m1/lab8/lab8.s: src/lab_m1/lab8/lab8.cpp.s
.PHONY : src/lab_m1/lab8/lab8.s

# target to generate assembly for a file
src/lab_m1/lab8/lab8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab8/lab8.cpp.s
.PHONY : src/lab_m1/lab8/lab8.cpp.s

src/lab_m1/lab9/lab9.o: src/lab_m1/lab9/lab9.cpp.o
.PHONY : src/lab_m1/lab9/lab9.o

# target to build an object file
src/lab_m1/lab9/lab9.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab9/lab9.cpp.o
.PHONY : src/lab_m1/lab9/lab9.cpp.o

src/lab_m1/lab9/lab9.i: src/lab_m1/lab9/lab9.cpp.i
.PHONY : src/lab_m1/lab9/lab9.i

# target to preprocess a source file
src/lab_m1/lab9/lab9.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab9/lab9.cpp.i
.PHONY : src/lab_m1/lab9/lab9.cpp.i

src/lab_m1/lab9/lab9.s: src/lab_m1/lab9/lab9.cpp.s
.PHONY : src/lab_m1/lab9/lab9.s

# target to generate assembly for a file
src/lab_m1/lab9/lab9.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/lab_m1/lab9/lab9.cpp.s
.PHONY : src/lab_m1/lab9/lab9.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/gl_utils.o: src/utils/gl_utils.cpp.o
.PHONY : src/utils/gl_utils.o

# target to build an object file
src/utils/gl_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/gl_utils.cpp.o
.PHONY : src/utils/gl_utils.cpp.o

src/utils/gl_utils.i: src/utils/gl_utils.cpp.i
.PHONY : src/utils/gl_utils.i

# target to preprocess a source file
src/utils/gl_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/gl_utils.cpp.i
.PHONY : src/utils/gl_utils.cpp.i

src/utils/gl_utils.s: src/utils/gl_utils.cpp.s
.PHONY : src/utils/gl_utils.s

# target to generate assembly for a file
src/utils/gl_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/gl_utils.cpp.s
.PHONY : src/utils/gl_utils.cpp.s

src/utils/text_utils.o: src/utils/text_utils.cpp.o
.PHONY : src/utils/text_utils.o

# target to build an object file
src/utils/text_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/text_utils.cpp.o
.PHONY : src/utils/text_utils.cpp.o

src/utils/text_utils.i: src/utils/text_utils.cpp.i
.PHONY : src/utils/text_utils.i

# target to preprocess a source file
src/utils/text_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/text_utils.cpp.i
.PHONY : src/utils/text_utils.cpp.i

src/utils/text_utils.s: src/utils/text_utils.cpp.s
.PHONY : src/utils/text_utils.s

# target to generate assembly for a file
src/utils/text_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GFXFramework.dir/build.make CMakeFiles/GFXFramework.dir/src/utils/text_utils.cpp.s
.PHONY : src/utils/text_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GFXFramework"
	@echo "... src/components/camera_input.o"
	@echo "... src/components/camera_input.i"
	@echo "... src/components/camera_input.s"
	@echo "... src/components/scene_input.o"
	@echo "... src/components/scene_input.i"
	@echo "... src/components/scene_input.s"
	@echo "... src/components/simple_scene.o"
	@echo "... src/components/simple_scene.i"
	@echo "... src/components/simple_scene.s"
	@echo "... src/components/text_renderer.o"
	@echo "... src/components/text_renderer.i"
	@echo "... src/components/text_renderer.s"
	@echo "... src/core/engine.o"
	@echo "... src/core/engine.i"
	@echo "... src/core/engine.s"
	@echo "... src/core/gpu/frame_buffer.o"
	@echo "... src/core/gpu/frame_buffer.i"
	@echo "... src/core/gpu/frame_buffer.s"
	@echo "... src/core/gpu/gpu_buffers.o"
	@echo "... src/core/gpu/gpu_buffers.i"
	@echo "... src/core/gpu/gpu_buffers.s"
	@echo "... src/core/gpu/mesh.o"
	@echo "... src/core/gpu/mesh.i"
	@echo "... src/core/gpu/mesh.s"
	@echo "... src/core/gpu/shader.o"
	@echo "... src/core/gpu/shader.i"
	@echo "... src/core/gpu/shader.s"
	@echo "... src/core/gpu/texture2D.o"
	@echo "... src/core/gpu/texture2D.i"
	@echo "... src/core/gpu/texture2D.s"
	@echo "... src/core/managers/texture_manager.o"
	@echo "... src/core/managers/texture_manager.i"
	@echo "... src/core/managers/texture_manager.s"
	@echo "... src/core/window/input_controller.o"
	@echo "... src/core/window/input_controller.i"
	@echo "... src/core/window/input_controller.s"
	@echo "... src/core/window/window_callbacks.o"
	@echo "... src/core/window/window_callbacks.i"
	@echo "... src/core/window/window_callbacks.s"
	@echo "... src/core/window/window_object.o"
	@echo "... src/core/window/window_object.i"
	@echo "... src/core/window/window_object.s"
	@echo "... src/core/world.o"
	@echo "... src/core/world.i"
	@echo "... src/core/world.s"
	@echo "... src/lab_m1/Tema1/Cloud.o"
	@echo "... src/lab_m1/Tema1/Cloud.i"
	@echo "... src/lab_m1/Tema1/Cloud.s"
	@echo "... src/lab_m1/Tema1/Explosion.o"
	@echo "... src/lab_m1/Tema1/Explosion.i"
	@echo "... src/lab_m1/Tema1/Explosion.s"
	@echo "... src/lab_m1/Tema1/Projectile.o"
	@echo "... src/lab_m1/Tema1/Projectile.i"
	@echo "... src/lab_m1/Tema1/Projectile.s"
	@echo "... src/lab_m1/Tema1/Tank.o"
	@echo "... src/lab_m1/Tema1/Tank.i"
	@echo "... src/lab_m1/Tema1/Tank.s"
	@echo "... src/lab_m1/Tema1/Tema1.o"
	@echo "... src/lab_m1/Tema1/Tema1.i"
	@echo "... src/lab_m1/Tema1/Tema1.s"
	@echo "... src/lab_m1/Tema1/Terrain.o"
	@echo "... src/lab_m1/Tema1/Terrain.i"
	@echo "... src/lab_m1/Tema1/Terrain.s"
	@echo "... src/lab_m1/Tema1/object2D1.o"
	@echo "... src/lab_m1/Tema1/object2D1.i"
	@echo "... src/lab_m1/Tema1/object2D1.s"
	@echo "... src/lab_m1/lab1/lab1.o"
	@echo "... src/lab_m1/lab1/lab1.i"
	@echo "... src/lab_m1/lab1/lab1.s"
	@echo "... src/lab_m1/lab2/lab2.o"
	@echo "... src/lab_m1/lab2/lab2.i"
	@echo "... src/lab_m1/lab2/lab2.s"
	@echo "... src/lab_m1/lab3/lab3.o"
	@echo "... src/lab_m1/lab3/lab3.i"
	@echo "... src/lab_m1/lab3/lab3.s"
	@echo "... src/lab_m1/lab3/lab3_vis2D.o"
	@echo "... src/lab_m1/lab3/lab3_vis2D.i"
	@echo "... src/lab_m1/lab3/lab3_vis2D.s"
	@echo "... src/lab_m1/lab3/object2D.o"
	@echo "... src/lab_m1/lab3/object2D.i"
	@echo "... src/lab_m1/lab3/object2D.s"
	@echo "... src/lab_m1/lab4/lab4.o"
	@echo "... src/lab_m1/lab4/lab4.i"
	@echo "... src/lab_m1/lab4/lab4.s"
	@echo "... src/lab_m1/lab5/lab5.o"
	@echo "... src/lab_m1/lab5/lab5.i"
	@echo "... src/lab_m1/lab5/lab5.s"
	@echo "... src/lab_m1/lab6/lab6.o"
	@echo "... src/lab_m1/lab6/lab6.i"
	@echo "... src/lab_m1/lab6/lab6.s"
	@echo "... src/lab_m1/lab7/lab7.o"
	@echo "... src/lab_m1/lab7/lab7.i"
	@echo "... src/lab_m1/lab7/lab7.s"
	@echo "... src/lab_m1/lab8/lab8.o"
	@echo "... src/lab_m1/lab8/lab8.i"
	@echo "... src/lab_m1/lab8/lab8.s"
	@echo "... src/lab_m1/lab9/lab9.o"
	@echo "... src/lab_m1/lab9/lab9.i"
	@echo "... src/lab_m1/lab9/lab9.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/gl_utils.o"
	@echo "... src/utils/gl_utils.i"
	@echo "... src/utils/gl_utils.s"
	@echo "... src/utils/text_utils.o"
	@echo "... src/utils/text_utils.i"
	@echo "... src/utils/text_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

